### ISSUE TITLE
Version incorrect in 1.5.1 tag

### ISSUE THREAD

**Issue by 0x6d617474** [wp-cli/wp-cli#4811]
The release tagged `1.5.1` has `2.0.0-alpha` in the `VERSION` file, and `wp --version` displays `2.0.0-alpha` instead of the expected `1.5.1`. 

See #4514 for a similar past issue.

**Comment by schlessera** [comment]
This should be fixed now in the latest release file for 1.5.1.

Sorry for the oversight!

**Comment by 0x6d617474** [comment]
I'm still seeing `2.0.0-alpha` in the `VERSION` file for the `1.5.1` tag, and in the `1.5.1` tar.gz file. It does appear to be fixed in the phar though.

**Comment by schlessera** [comment]
@0x6d617474 Thanks, I've retagged the correct version. This should be fixed as well now.
