### ISSUE TITLE
Brew install fails for version 1.5.1

### ISSUE THREAD

**Issue by andtos90** [wp-cli/wp-cli#4813]
It looks like the .phar file is missing for the latest version:
```
> brew install wp-cli
==> Downloading https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "wp-cli"
Download failed: https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar
```

**Comment by schlessera** [comment]
Thanks, @andtos90.
This is a temporary issue while I retag the packages to fix an issue with the 1.5.1 build (see #4811).
I'll ping you in here as soon as the issue is resolved.

**Comment by andtos90** [comment]
It's working now, thanks

**Comment by dougshults** [comment]
Seems to be an issue still 
`Download failed: https://dl.bintray.com/homebrew/mirror/wp-cli-1.5.1.phar`
