### ISSUE TITLE
[PHP 8] FATAL: missing symfony/polyfill-mbstring/Resources/mb_convert_variables.php8

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#5479]
latest alpha (can't tell you the exact version, since wp cli version itself doesn't work)

Run any command, get this issue:
(I'm on PHP8.0RC5)

```
Failed opening required phar:///usr/bin/wp/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8 (include_path=.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php)
File: phar:\\\usr\bin\wp\vendor\symfony\polyfill-mbstring\bootstrap.php on line 115
Error URL: no-host (request in phar: directory)
Server: hetznercloud-fsn1-dc8-1.optimiseroute.com
Trace:
#0 phar:///usr/bin/wp/vendor/composer/autoload_real.php (71): require()
#1 phar:///usr/bin/wp/vendor/composer/autoload_real.php (61): composerRequire27fcc3710ec882e42a5e96dbef941a4d( $fileIdentifier = 0e6d7bf4a5811bfa5cf40c5ccd6fae6a, $file = phar:///usr/bin/wp/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php )
#2 phar:///usr/bin/wp/vendor/autoload.php (7): ComposerAutoloaderInit27fcc3710ec882e42a5e96dbef941a4d::getLoader()
#3 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php (49): require( phar:///usr/bin/wp/vendor/autoload.php )
#4 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php (75): WP_CLI\Bootstrap\AutoloaderStep->process( $state = WP_CLI\Bootstrap\BootstrapState Object )
#5 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php (27): WP_CLI\bootstrap()
#6 phar:///usr/bin/wp/php/boot-phar.php (11): include( phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php )
#7 /usr/bin/wp (4): include( phar:///usr/bin/wp/php/boot-phar.php )
```

**Comment by kkmuffme** [comment]
It seems this is not a PHP 8 issue, but a bug in the nightly that affects all PHP versions.
When trying to reinstall the nightly, I get:

```
 wp cli update --nightly
You have version 2.4.0. Would you like to update to the latest nightly? [y/n] y
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
md5 hash verified: 47292fdd2af91d1b553580c42494ce35

Error: The downloaded PHAR is broken, try running wp cli update again.
```

**Comment by schlessera** [comment]
@kkmuffme I assume this was fixed with https://github.com/wp-cli/wp-cli-bundle/pull/261/files. Can you try again and confirm?

**Comment by nb** [comment]
@schlessera unfortunately this still fails for me:

* Running PHP 8.0.0 on MacOS.
* On latest nightly (2021-02-01).

Both when I run `wp cli update --nightly` (using 2.4) and when I download the nightly manually and run any `wp` command I get the exact same error as @kkmuffme.

Thanks! Let me know if I can provide more debug information.

**Comment by Jarlskov** [comment]
I'm also still experiencing this. Is this included in the current nightly?

**Comment by schlessera** [comment]
@Jarlskov No, this will be fixed by https://github.com/wp-cli/wp-cli-bundle/pull/263. Looking to get that one in today.

**Comment by kkmuffme** [comment]
@Jarlskov @nb would you be so kind to confirm if you still get this error?

I see https://github.com/wp-cli/wp-cli-bundle/pull/263 was merged, but when updating with nightly, I get the same alpha version. Since I don't have a PHP8 environment available right now, I cannot test it.

**Comment by nb** [comment]
@kkmuffme it works for me now:

```
🐻  → wp cli info                                                                                                                                                                                                                                                          ~:endangered:
OS:	Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/8.0.6/bin/php
PHP version:	8.0.6
php.ini used:	/usr/local/etc/php/8.0/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 14.14 Distrib 5.7.32, for osx10.12 (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/nb
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.5.0-alpha-3b61391
```

**Comment by Jarlskov** [comment]
```
~# php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 08:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

```
~# wp cli info
OS:	Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.3
php.ini used:	/etc/php/8.0/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.5.0-alpha-3b61391
```

I still see various errors, but generally, the current nightly seems mostly working for me

```
Warning: chmod(): Operation not permitted in /var/www/frabunden.dk/wp-admin/includes/class-wp-filesystem-direct.php on line 173
PHP Warning:  chmod(): Operation not permitted in /var/www/frabunden.dk/wp-admin/includes/class-wp-filesystem-direct.php on line 173
```

```
PHP Warning:  Trying to access array offset on value of type int in /var/www/levemand.dk/wp-includes/formatting.php on line 884
Warning: Trying to access array offset on value of type int in /var/www/levemand.dk/wp-includes/formatting.php on line 884
```
