### ISSUE TITLE
wp language core install fails on PHP8

### ISSUE THREAD

**Issue by ratzrattillo** [wp-cli/wp-cli#5494]
Hello there!

Installing of languages fails when using wordpress and wp-cli with PHP8:

`bash-5.1$ wp language core install de_DE_formal
Fatal error: Declaration of WP_CLI\LanguagePackUpgrader::download_package($package, $check_signatures = false) must be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = []) in phar:///usr/local/bin/wp/vendor/wp-cli/language-command/src/WP_CLI/LanguagePackUpgrader.php on line 51`

**System-Info:**
`bash-5.1$ wp --info
OS:     Linux 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64
Shell:
PHP binary:     /usr/local/bin/php
PHP version:    8.0.1
php.ini used:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
`

**Comment by webdock-io** [comment]
This seems to be related to https://github.com/wp-cli/core-command/pull/166 

We see this happening for us when installing WP using WP-CLI in basically any other language version other than English US

From what I can tell this is happening on other PHP versions. My guess is that the language-specific versions that WP-CLI downloads do not have the same signature as the default English US version of WP.

The solution for now, for us, is to always install English US and then change the language after installation.

**Comment by wojsmol** [comment]
This is related to php function declaratiON and was fixed long time ago in nightly version of WP-CLI - both for [core](https://github.com/wp-cli/core-command/pull/166) and [language](https://github.com/wp-cli/language-command/pull/100) commends.

**Comment by webdock-io** [comment]
@wojsmol Not true. This is still a problem. Easily reproducible on Ubuntu Focal with the following steps. However, I mis-spoke earlier w/regards to how this is reproducible - this happens if you install core in en_US and then later try to run `language install`

Commands below abbreviated with "..." as it's all just standard stuff.

Install WP-CLI according to official guidelines:

`# wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp`

Download the core in en_US

`# wp core download --locale=en_US ...`

Set Config

`# wp config create ...`

Core install

`# wp core install ...`

And now try to install/activate  another language like da_DK

`# wp core language install da_DK ...`

Crash :O)

```
PHP Fatal error:  Declaration of WP_CLI\LanguagePackUpgrader::download_package($package, $check_signatures = false) must be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = []) in phar:///usr/local/bin/wp/vendor/wp-cli/language-command/src/WP_CLI/LanguagePackUpgrader.php on line 51
Fatal error: Declaration of WP_CLI\LanguagePackUpgrader::download_package($package, $check_signatures = false) must be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = []) in phar:///usr/local/bin/wp/vendor/wp-cli/language-command/src/WP_CLI/LanguagePackUpgrader.php on line 51
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
```

**Comment by wojsmol** [comment]
@webdock-io This is expected because` # wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp ` downloads still version 2.4.0 of WP-CLI witch don't contain PR mentioned in https://github.com/wp-cli/wp-cli/issues/5494#issuecomment-767527651

**Comment by webdock-io** [comment]
@wojsmol Not sure if it's "expected" by end users who follow official guidelines from here:

https://wp-cli.org/#installing

And then get an old-as-balls version of wp-cli installed? :)

Do you know how  we get our hands on up-to-date stable releases with a "scriptable" (i.e. does not change abritrarily) URL ?

**Comment by ocean90** [comment]
@webdock-io It is expected because what you see here is an issue with the current stable version (2.4.0). The issue though has been fixed already but there's no new stable version yet. To verify this you can run `wp cli update --nightly` which will install a snapshot of the upcoming version (2.5.0).

**Comment by webdock-io** [comment]
@ocean90 Great, that clarifies it. Thanks :)

Do you happen to know when 2.5.0 hits stable? Given how long leadtime there seems to be between releases I am almost tempted to switch to nightly - but in a production environment that might be a bad idea.

For now we limit users to en_US - and if 2.5.0 is coming soon we'd just stick with this solution until it lands, I think.

Thanks for the information.!

**Comment by tristanbes** [comment]
Yup, using a nightly in a production environement is a bad idea.
We're also in the situation where we need a stable 2.5.0 tag with Composer2 support. 

Seems like everything is ready to be tagged: https://github.com/wp-cli/wp-cli-bundle/issues/187
I hope the v2.5.0 is tagged soon.

**Comment by andrejcremoznik** [comment]
@wojsmol The package that `wp cli update --nightly` downloads is broken, at least on php8. Downloading it manually and running it I get the dump below. I really hope a new version is released soon because there are numerous issues with `2.4.0`. What happened to the 3-4 month release cadence?

```
PHP Warning:  require_once(phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8): Failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8" is not a file in phar "/home/dev/bin/wp" in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115

Warning: require_once(phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8): Failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8" is not a file in phar "/home/dev/bin/wp" in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115
PHP Fatal error:  Uncaught Error: Failed opening required 'phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8' (include_path='.:') in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php:115
Stack trace:
#0 phar:///home/dev/bin/wp/vendor/composer/autoload_real.php(71): require()
#1 phar:///home/dev/bin/wp/vendor/composer/autoload_real.php(61): composerRequire123e1944cad69e3ca35f2bec23f6dbf7()
#2 phar:///home/dev/bin/wp/vendor/autoload.php(7): ComposerAutoloaderInit123e1944cad69e3ca35f2bec23f6dbf7::getLoader()
#3 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('...')
#4 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\AutoloaderStep->process()
#5 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///home/dev/bin/wp/php/boot-phar.php(11): include('...')
#7 /home/dev/bin/wp(4): include('...')
#8 {main}
  thrown in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115

Fatal error: Uncaught Error: Failed opening required 'phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8' (include_path='.:') in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php:115
Stack trace:
#0 phar:///home/dev/bin/wp/vendor/composer/autoload_real.php(71): require()
#1 phar:///home/dev/bin/wp/vendor/composer/autoload_real.php(61): composerRequire123e1944cad69e3ca35f2bec23f6dbf7()
#2 phar:///home/dev/bin/wp/vendor/autoload.php(7): ComposerAutoloaderInit123e1944cad69e3ca35f2bec23f6dbf7::getLoader()
#3 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('...')
#4 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\AutoloaderStep->process()
#5 phar:///home/dev/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///home/dev/bin/wp/php/boot-phar.php(11): include('...')
#7 /home/dev/bin/wp(4): include('...')
#8 {main}
  thrown in phar:///home/dev/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115
```

**Comment by ratzrattillo** [comment]
Same issue for me as for @andrejcremoznik

**Comment by alexholt** [comment]
wp-cli-bundle is restricting the vendor includes to just the php file extension and we have here a file named mb_convert_variables.php8.

I opened a PR. The following works if you want to get up and running with php8 quickly.

```
git clone --depth 1 --branch handle-php8-file-extension https://github.com/alexholt/wp-cli-bundle
cd wp-cli-bundle
composer install
php -dphar.readonly=0 utils/make-phar.php wp.phar
cp wp.phar /usr/bin/wp
```

**Comment by strarsis** [comment]
When will WP CLI `2.5.0` (currently nightly) become the new WP CLI stable (currently `2.4.0`)?

**Comment by alexholt** [comment]
Good question. @schlessera is there something we can do to help get 2.5 to stable?

**Comment by schlessera** [comment]
I'm currently wrapping everything up around v2.5.0, as all upstream blockers have been resolved, so expect it to be published in the coming days.

I'm closing this issue, as this is fixed in the current state of the code. If you notice a similar issue with the current nightly or current `master` branch, please open a new issue.

**Comment by MaximeCulea** [comment]
Hi there, 
Using PHP 8.0 and 8.1, I still got this issue with wp-cli in the version downloaded from official repo (WP-CLI 2.6.0).
Using the nightly version is working fine tho (what is the diff btw?).

**Comment by wojsmol** [comment]
@MaximeCulea Please opem new issue for this with exact error message.
