### ISSUE TITLE
Proxy settings being ignored

### ISSUE THREAD

**Issue by idl0r** [wp-cli/wp-cli#6160]
It looks like wp-cli completely ignores proxy settings.
We've tried different ways of configuration, like global or local yaml file, via environment variables, via wodpress config, via CLI.

The proxy is already set in wp-config.php and seems to work fine so far except with wp-cli.
Setting those options e.g. by --requires=/path/to/additional-php-stuff.php emits a warning about the constants already being defined but doesn't seem to help anyway.
So no luck either.
We tried environment variables like the common "http_proxy" as well as WP_PROXY_HOST / WP_PROXY_PORT as well as defining those in the mentioned PHP file, WP config, YAML files.

Steps to reproduce:

- Have a VM, container or whatever and disable internet communication by firewall
- Have a working proxy
- Try e.g. curl against google or wordpress.org using your proxy: `curl -s --proxy proxy.example.com:3128 https://downloads.wordpress.org -o /dev/null`
- You may also run a `tcpdump -ni any port 443` while you try to run "wp core update", "wp cli check-update" or whatever else does external HTTP requests
- Get errors about running into timeout (in case the firewall just drops, instead of reject)
- `Error: Failed to get url 'https://api.github.com/repos/wp-cli/wp-cli/releases?per_page=100': cURL error 28: Failed to connect to api.github.com port 443 after 10000 ms: Timeout was reached.`
- `Error: Failed to get url 'https://downloads.wordpress.org/release/wordpress-6.9-no-content.zip': cURL error 28: Failed to connect to downloads.wordpress.org port 443 after 10000 ms: Timeout was reached.`
- Notice traffic on the above tcpdump triggered by "wp"

wp cli doesn't use the proxy at all it seems. wp core update seems to, kinda, but somehow mixes up requests via proxy and without it. Like I can see requests to api.wordpress.org via proxy which work and those to the actual download are made without the proxy.

```
OS:	Linux 6.1.0-41-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.158-1 (2025-11-09) x86_64
Shell:	/usr/sbin/nologin
PHP binary:	/usr/bin/php8.2
PHP version:	8.2.29
php.ini used:	/etc/php/8.2/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 8.0.44 for Linux on x86_64 (MySQL Community Server - GPL)
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/example/wordpress
WP-CLI packages dir:	/var/www/.wp-cli/packages/
WP-CLI cache dir:	/var/www/.wp-cli/cache
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.11.0
```

php-curl is also installed.
No suhosin. No wp packages installed.

**Comment by swissspidy** [comment]
This looks like a duplicate of https://github.com/wp-cli/wp-cli/issues/3019 and https://github.com/wp-cli/core-command/issues/292

**Comment by idl0r** [comment]
We have php-curl installed. We tried many different variants and none worked.

**Comment by swissspidy** [comment]
I hear you.

To summarize those other issues:

The tl;dr of that conversation:

* php-curl honors the http_proxy env var, so there is some different behavior when not using curl
* Requests defers honoring that env var to the library user (e.g., WordPress core or WP-CLI) (see also https://github.com/WordPress/Requests/issues/218)
* WP-CLI doesn't want to blindly trust that env var
* WP-CLI does not contain any special handling for proxies in general
* WP core supports `WP_PROXY_*` _constants_ (not env vars or anything else) for controlling proxy settings in Requests
* WP-CLI uses standard WP core functionality wherever possible

... That's why it seems to you to sometimes work and sometimes not, depending on whether it goes through core code or not

**Comment by swissspidy** [comment]
For enabling the HTTP proxy configuration support in WP-CLI, @ekamran has kindly built and shared https://github.com/ekamran/wp-cli-http-proxy-command today. If you're interested, I recommend giving it a try and providing feedback.

**Comment by idl0r** [comment]
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires ekamran/wp-cli-http-proxy-command dev-main -> satisfiable by ekamran/wp-cli-http-proxy-command[dev-main].
    - ekamran/wp-cli-http-proxy-command dev-main requires wp-cli/wp-cli ^2.13 -> found wp-cli/wp-cli[2.12.0] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
```

2.13 hasn't been released tho. This is a production system so I actually didn't want to experiment that much there.

**Comment by swissspidy** [comment]
That's fair. The nightly is typically very stable, but you could of course also download the Phar separately without affecting the main `wp`. Alternatively, the new release should be hopefully out soon.

**Comment by ekamran** [comment]
Thanks for testing and pointing this out. You were right, the Composer constraint was too strict.

I have updated the package so it now supports WP-CLI 2.12.0 as well:
https://github.com/ekamran/wp-cli-http-proxy-command

I also tested it locally by installing it with wp-cli/wp-cli 2.12.0 in a fresh Composer project, and Composer resolved it successfully.

@idl0r

**Comment by idl0r** [comment]
@ekamran not sure if I should open a new issue instead but:

```
wp core verify-checksums
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_CLI\HttpProxy\Bootstrap::WP_CLI\HttpProxy\{closure}(), 1 passed in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 331 and exactly 3 expected in /var/www/.wp-cli/packages/vendor/ekamran/wp-cli-http-proxy-command/src/Bootstrap.php:63
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php(331): WP_CLI\HttpProxy\Bootstrap::WP_CLI\HttpProxy\{closure}()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(835): WP_CLI::do_hook()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/WpOrgApi.php(338): WP_CLI\Utils\http_request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/WpOrgApi.php(305): WP_CLI\WpOrgApi->get_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/WpOrgApi.php(116): WP_CLI\WpOrgApi->json_get_request()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/checksum-command/src/Checksum_Core_Command.php(117): WP_CLI\WpOrgApi->get_core_checksums()
#6 [internal function]: Checksum_Core_Command->__invoke()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(497): call_user_func()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(470): WP_CLI\Dispatcher\Subcommand->invoke()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(493): WP_CLI\Runner->run_command()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(136): WP_CLI\Runner->run_command_and_exit()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1228): WP_CLI\Runner->do_early_invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(84): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(35): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in /var/www/.wp-cli/packages/vendor/ekamran/wp-cli-http-proxy-command/src/Bootstrap.php on line 63
```

**Comment by ekamran** [comment]
@idl0r 

Thanks for testing and sharing the stack trace.

You were right, this was a bug in the package. WP-CLI 2.12 passes only the request options to this hook, while current WP-CLI main passes extra request details too.

I have updated the package so the callback works with both WP-CLI 2.12 and current main. I tested it locally with a fresh WP-CLI 2.12.0 install and also with current main, and the fatal is gone.

**Comment by idl0r** [comment]
That looks good at the first glance so far.
Only
```
PHP Warning:  Constant WP_PROXY_HOST already defined in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1334) : eval()'d code on line 85
PHP Warning:  Constant WP_PROXY_PORT already defined in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1334) : eval()'d code on line 86
```
Not a big deal tho.
It may be because it's defined in wp-config.php. Not sure if PHP has an ifdef or something like that, to silence those otherwise it looks promising. It should be part of wp / core tho, IMO.

**Comment by ekamran** [comment]
Thanks, that warning makes sense.

I updated the package again. Now it waits until wp-config.php is loaded before defining WordPress proxy constants. So if WP_PROXY_HOST or WP_PROXY_PORT are already defined in wp-config.php, the package leaves them as-is.

I also made WP-CLI requests use those existing constants after wp-config.php loads, so there is no mixed proxy config between wp-config.php and wp-cli.yml.

Added a regression test for this case too.

And yes, I agree this probably belongs in WP-CLI/core eventually. For now I am keeping this package as a small place where we can test the behaviour safely.

**Comment by idl0r** [comment]
Ok, so while more things are working now with the package, some are still not, unfortunately, sorry:
```
wp package update
Using Composer to update packages...
---
Loading composer repositories with package information
Warning: curl error 28 while downloading https://wp-cli.org/package-index/packages.json: Failed to connect to wp-cli.org port 443 after 10004 ms: Timeout was reached
---
Error: Failed to update packages.

wp package list
Warning: curl error 28 while downloading https://wp-cli.org/package-index/packages.json: Failed to connect to wp-cli.org port 443 after 10003 ms: Timeout was reached
+-----------------------------------+---------+----------+--------+----------------+
| name                              | authors | version  | update | update_version |
+-----------------------------------+---------+----------+--------+----------------+
| ekamran/wp-cli-http-proxy-command |         | dev-main | error  | error          |
+-----------------------------------+---------+----------+--------+----------------+
```

I wanted to update, to get the latest version, including those constant fixes and that's what I got. Stuff like checking the checksums and stuff, also using external connections, works fine and still issues those constant warnings.
So since the constant warnings are missing in the first two ones, I suppose it's not respected / loaded at that stage. Hope it helps.

**Comment by ekamran** [comment]
I checked this locally too. The package commands seem to use WP-CLI's Composer/package manager path, not the normal WP-CLI HTTP request helper that the package currently hooks into.

So the package is helping with Requests-based calls like checksums, but wp package list/update looks like a separate Composer/package-index path. I do not want to guess a workaround here because it may need support inside WP-CLI's package manager itself.

Also, if wp package update cannot run, you may still be on the previous package version, so the constant warning fix may not be installed yet.
